# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtAqahlB7JeGeMu_RUAMzmRO8UedGPBP
"""

import yfinance as yf
import json
import sys

symbol = sys.argv[1]
stock = yf.Ticker(symbol)

change = stock.info['currentPrice'] - stock.info['previousClose']
dictionary = { 
  '02. open': stock.info['open'],
  '03. high': stock.info['dayHigh'],
  '04. low': stock.info['dayLow'],
  '05. price': stock.info['currentPrice'],
  '06. volume': stock.info['volume'],
  '07. latest trading day': 'Fri',
  '08. previous close': stock.info['previousClose'],
  '09. change': f'{change:.2f}'
 }

jsonDump = json.dumps(dictionary)

print(jsonDump)
sys.stdout.flush()